<script lang="ts">
  let props = $props<{ movie: any }>();
  
  // This would be generated by AI based on user preferences
  const recommendationReason = $state<string>(
    `Based on your viewing history and preferences, our AI thinks you'll enjoy this title. 
    You've previously watched similar titles in the ${props.movie.genres?.join(', ')} genres, 
    and this movie has been highly rated by users with similar taste profiles.`
  );

  function askAIToExplain() {
    // Navigate to chat with context for explaining recommendation
    window.location.href = `/chat?context=recommend&id=${props.movie.id}`;
  }
</script>

<div class="w-72 bg-surface-200-800/60 mb-8 rounded-xl p-6 mx-auto md:mx-0">
  <h2 class="mb-3 text-xl font-semibold flex items-center gap-2">
    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="text-emerald-400">
      <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"/>
      <polyline points="22 4 12 14.01 9 11.01"/>
    </svg>
    AI Match
  </h2>
  <p class="text-gray-300 leading-relaxed">{recommendationReason}</p>
  
  <button 
    onclick={askAIToExplain}
    class="mt-4 text-primary-500 hover:text-primary-400 flex items-center gap-1 text-sm transition"
  >
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
      <path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"/>
    </svg>
    Ask AI to explain why
  </button>
</div>